{ pkgs, ... }:

let
  tex =
    (pkgs.texlive.combine { inherit (pkgs.texlive) scheme-full tikz-feynman; });
in {
  environment = {
    systemPackages = with pkgs; [
      arduino
      baobab
      bash
      bat
      bitwarden
      bottles
      btop
      calibre
      cava
      cbatticon
      cmake
      coreutils
      darktable
      distrobox
      dotnet-sdk_7
      dunst
      element-desktop
      emacs-all-the-icons-fonts
      eww
      eza
      fd
      feh
      ffmpeg
      ffmpegthumbnailer
      freetube
      gcc
      ghostscript
      gimp
      gnome.file-roller
      gnome.gnome-disk-utility
      gnome.nautilus
      gnome.simple-scan
      gnumake
      gnuplot
      google-chrome
      gource
      graphviz
      gthumb
      gtklock
      handbrake
      hplip
      htop
      ifuse
      imagemagick
      inkscape
      ipfs
      ispell
      jq
      kdenlive
      kmonad
      krita
      libheif
      libimobiledevice
      libnotify
      libreoffice
      libsecret
      lynis
      maim
      mono
      neofetch
      networkmanagerapplet
      nicotine-plus
      nil
      nix-index
      nix-tree
      nixfmt
      nixos-generators
      nmap
      nodejs
      nvd
      ollama
      onefetch
      openai-whisper
      openimagedenoise
      openjdk
      openssl
      p7zip
      pandoc
      pciutils
      poppler_utils
      ps_mem
      python311Full
      qbittorrent
      qemu
      qpwgraph
      remmina
      ripgrep
      rofi-wayland
      scid
      smartmontools
      socat
      solaar
      speedtest-cli
      sqlite
      stockfish
      sway-contrib.grimshot
      swaybg
      tesseract
      tex
      tmux
      tokei
      trash-cli
      tree-sitter
      unrar
      unzip
      usbutils
      vim
      virt-manager
      vorta
      wayland
      wget
      wl-clipboard
      wpa_supplicant
      xterm
      yt-dlp
      yubikey-agent
      yubikey-manager
      yubikey-manager-qt
      yubikey-personalization
      yubikey-personalization-gui
      yubikey-touch-detector
      zathura
    ];
  };
}
